### ISSUE TITLE
Alt-Q does not stop playback - repeats clipboard contents 

### ISSUE THREAD

**Issue by jesherman** [jame25/Piper-Tray#1]
After installing Piper_Tray (copied sox.zip, voice.onnx, voice.json, and piper.zip contents into piper_tray folder) it would immediately start playing whatever contents are stored in the clipboard.

Pressing Alt-Q restarts playback of the clipboard contents. It does not stop / pause / play playback for me.

**Comment by jame25** [comment]
Hi, thanks for the report. Can I just confirm, are you running the latest version (v1.1.1)?

**Comment by jesherman** [comment]
Yes - i just downloaded piper-tray in the last hour

I see "logging=false" - does marking this true provide any debug info?

**Comment by jame25** [comment]
Yes. An error.log should be generated if there is a serious issue. Can I ask, does the 'Stop Speech' option work?

**Comment by jesherman** [comment]
stop speech from the tray works fine 

setting logging=true does not generate error.log  (at least i dont see the file in the folder)

I am also getting a crash but I will report that separately.

**Comment by jesherman** [comment]
fixed!
