### ISSUE TITLE
No sound is getting produced

### ISSUE THREAD

**Issue by andris1** [jame25/Piper-Tray#12]
I extracted the files like so:
![image](https://github.com/user-attachments/assets/000d09b1-5382-44eb-a1f4-d8c87f0ee563)

I have the runtime installed, I have monitoring enabled.

Yet selecting the text and ctrl+c adding it clipboard does nothing.

**Comment by jame25** [comment]
Hello. The issue appears to be the naming of the voice model json in your directory. It should match the .onnx.

Corrected name: `en_US-libritts_r-medium.onnx.json`

**Comment by andris1** [comment]
Wonderful, that worked! Thanks for the help.
