### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by jesherman** [jame25/Piper-Tray#2]
Pressing Alt Q randomly crashes the app (disappears from tray)

No error.log or real way to repro, just randomly seems to occur while running the crash.

Not sure how to debug further to find root cause.

if helpful i can zip up and share my folder contents

**Comment by jame25** [comment]
This crash is probably related to the fact that the hotkey was hard-coded to US keyboard layout. This should now be resolved in [v1.1.2](https://github.com/jame25/Piper-Tray/releases/tag/v1.1.2), but let me know if you still experience the crash.

**Comment by jesherman** [comment]
crash still repros on 1.1.2 when using alt-q in repeat succession

**Comment by jame25** [comment]
Please try this test version when you get the chance: https://github.com/jame25/Piper-Tray/releases/tag/v1.1.3

**Comment by jesherman** [comment]
working great now thanks!
