### ISSUE TITLE
[Enhancement] Voices switching

### ISSUE THREAD

**Issue by agiz10** [jame25/Piper-Tray#3]
Selecting voices from tray would be useful for multi-language setup.

One would first need to define voices in settings.conf and then switch between different voices via tray menu.
Switch voices with keyboard shortcuts would be great too (also defined in settings.conf). At least 3 keys like CTRL+ ALT+ S or something similar.

**Comment by jame25** [comment]
Try the new release and let me know what you think.
https://github.com/jame25/Piper-Tray/releases/tag/v1.1.5

**Comment by agiz10** [comment]
Sweet. That works nicely, thx!
Keyboard shortcuts for most settings would be a bonus if you get around to it.
