### ISSUE TITLE
[Enhancement] Speech rate 

### ISSUE THREAD

**Issue by agiz10** [jame25/Piper-Tray#4]
Speech rate setting in tray and via keyboard shortcuts would be great in addition to settings.conf file.

**Comment by jame25** [comment]
Try the new release and let me know what you think.
https://github.com/jame25/Piper-Tray/releases/tag/v1.1.6

**Comment by agiz10** [comment]
It works in tray, thank you.
There are some instances when it does not work (the "," vs "." delimiter is the culprit), but i have not figured the logic yet to reproduce it.
Now all we need is keyboard shortcuts.

**Comment by jame25** [comment]
Try the new release and let me know what you think. Hotkeys are now configurable:

![Capture](https://github.com/user-attachments/assets/796b1fa4-4998-401f-b0f8-8f45a2d0bfea)

https://github.com/jame25/Piper-Tray/releases/tag/v2.0.0
