### ISSUE TITLE
[Enhancement] Speaker Selection

### ISSUE THREAD

**Issue by Prar-Alexander** [jame25/Piper-Tray#8]
The addition of a variable within the configuration file for selecting the speaker in multi-speaker models.

**Comment by jame25** [comment]
Try the latest release and let me know what you think.
https://github.com/jame25/Piper-Tray/releases/tag/v2.0.1

**Comment by Prar-Alexander** [comment]
When manually added to the config before the application launches or typed in the settings menu, it works for the session. However, pipertray will save into the config as 0.

**Comment by jame25** [comment]
Working to resolve this asap.

**Comment by jame25** [comment]
Try this version: https://github.com/jame25/Piper-Tray/releases/tag/v2.0.7

**Comment by Prar-Alexander** [comment]
The Speaker ID is now correctly listed and saved. However, it will not apply the Speaker without activating a preset, even when already listed as active. This occurs on launch, where it will use the default speaker, and when changing the speaker ID from the settings menu, it will continue to use the previous speaker.

**Comment by Prar-Alexander** [comment]
All expected functionality seems to be added now:
- Support for multi-speaker Models
- Speaker selection dialog
- List of Speakers
- Responsive to Speaker setting changes.
